const TEST_CATALOG = {
    "Creatinine Test": { price: 120, code: "CRE" },
    "Glucose Random Test": { price: 90, code: "GRT" },
    "Estradiol Test (E2)": { price: 480, code: "EST" },
    "Reducing Substances, Paediatric Urine Test": { price: 150, code: "RSU" },
    "SGOT / AST Test": { price: 150, code: "AST" },
    "Lactate Dehydrogenase (LDH), Serum Test": { price: 260, code: "LDH" },
    "HCG Tumor Marker (Cancer) Test": { price: 570, code: "HCG" },
    "TSH 3rd Generation Test": { price: 190, code: "TSH" },
    "Urine Glucose Fasting Test": { price: 90, code: "UGF" },
    "HIV 1&2 Antibodies Test by CMIA Method": { price: 420, code: "HIV" },
    "Hemoglobin & Hematocrit Test": { price: 160, code: "HHT" },
    "Adenosine Deaminase (ADA) Test, Serum": { price: 520, code: "ADA" },
    "CRP Test (C Reactive Protein Test)": { price: 350, code: "CRP" },
    "Glucose Fasting Test": { price: 90, code: "GFT" },
    "Blood Urea Test": { price: 110, code: "BUT" },
    "Glucose Challenge Test (GCT)- 50 Grams Of Glucose": { price: 90, code: "GCT" },
    "Urine Sugar Random Test": { price: 90, code: "USR" },
    "Stool for Hanging Drop preparation Test": { price: 220, code: "SHD" },
    "Albumin Test": { price: 130, code: "ALB" },
    "Calcium Test": { price: 170, code: "CAL" },
    "Iron Studies Test": { price: 480, code: "IST" },
    "Cytology For Malignant Cells Test": { price: 180, code: "CMC" },
    "Hepatitis C antibody (HCV) Test - Rapid card": { price: 220, code: "HCV" },
    "Hemodialysis Water Culture": { price: 920, code: "HWC" },
    "Stool pH & Reducing Substances Test": { price: 130, code: "SPH" },
    "Pancreatitis Lipase Test": { price: 550, code: "PLT" },
    "Thyroid Profile Free Test": { price: 480, code: "TPF" },
    "Albert Stain Test (Diphtheria)": { price: 220, code: "AST" },
    "Prothrombin time (pt) Test": { price: 310, code: "PTT" },
    "Absolute Eosinophil Count (AEC) Test": { price: 130, code: "AEC" },
    "Vitamin D Test": { price: 570, code: "VDT" },
    "Rheumatoid Factor (RA) Quantitative Test": { price: 350, code: "RAF" },
    "Urine Culture Test": { price: 610, code: "UCT" },
    "Urine Glucose PP Test": { price: 90, code: "UGP" },
    "HDL Cholesterol Direct Test": { price: 230, code: "HDL" },
    "HIV Antibody, Rapid Card Test": { price: 350, code: "HAR" },
    "Gram Stain Test": { price: 260, code: "GST" },
    "Potassium, Spot Urine Test": { price: 220, code: "PSU" },
    "Pancreatitis Amylase Test": { price: 350, code: "PAT" },
    "Complete Blood Count (CBC) Test": { price: 260, code: "CBC" },
    "Stool Routine & Microscopic Examination": { price: 110, code: "SRM" },
    "Acid Fast Bacilli (AFB) Test (3 Samples)": { price: 180, code: "AFB" },
    "Iron Test": { price: 220, code: "IRN" },
    "Cholesterol Profile": { price: 310, code: "CHP" },
    "Calcium Ionised Serum Test": { price: 440, code: "CIS" },
    "Creatinine Spot Urine Test": { price: 220, code: "CSU" },
    "Liver Function Test (LFT)": { price: 350, code: "LFT" },
    "FT3 (Free Triiodothyronine 3) Test": { price: 260, code: "FT3" },
    "Reticulocyte Count Test": { price: 260, code: "RCT" },
    "Urine Bile Salt & Bile Pigments Test": { price: 90, code: "UBS" },
    "Pericardial Fluid Analysis Test": { price: 180, code: "PFA" },
    "Triglycerides Test": { price: 170, code: "TGT" },
    "Microalbuminuria 24Hrs Urine Test": { price: 480, code: "MAU" },
    "Total Protein Test": { price: 110, code: "TPT" },
    "Magnesium 24 Hrs Urine Test": { price: 480, code: "MGU" },
    "Absolute Neutrophil Count (ANC) Test": { price: 140, code: "ANC" },
    "WIDAL Test By Tube Agglutination": { price: 180, code: "WTA" },
    "Albumin Test by Spot Urine": { price: 90, code: "ASU" },
    "Vitamin B12 Test": { price: 480, code: "VB12" },
    "Acetone Urine (Qualitative) Test": { price: 310, code: "AUQ" },
    "Absolute Lymphocyte Count Blood Test": { price: 150, code: "ALC" },
    "Creatinine Body Fluid Test": { price: 220, code: "CBF" },
    "Microalbuminuria Spot Urine Test": { price: 480, code: "MSU" },
    "Total Protein & Albumin/globulin (ag) Ratio Test": { price: 130, code: "TPA" },
    "Uric Acid Test": { price: 140, code: "UAT" },
    "Uric Acid, Spot urine Test": { price: 240, code: "UAS" },
    "Synovial/Joint Fluid Analysis Test": { price: 180, code: "SFA" },
    "Ferritin Test": { price: 350, code: "FER" },
    "Chloride, Urine Test": { price: 170, code: "CLU" },
    "Follicle Stimulating Hormone FSH Test": { price: 440, code: "FSH" },
    "CBC with PS Test": { price: 260, code: "CPS" },
    "Urine Calcium & Creatinine Ratio Test": { price: 150, code: "UCR" },
    "Electrolytes (Na/K/Cl), Urine Test": { price: 310, code: "ELU" },
    "PAP (Papanicolaou) Smear Test": { price: 440, code: "PAP" },
    "Kidney Function Test (KFT)": { price: 350, code: "KFT" },
    "Absolute Basophils Count Blood Test": { price: 150, code: "ABC" },
    "HBA1C Test": { price: 260, code: "HBA" },
    "Typhoid Test IGM Test": { price: 350, code: "TTI" },
    "Total T4 (Thyroxine) Test": { price: 180, code: "TT4" },
    "Cholesterol Total Body Fluid Test": { price: 220, code: "CTB" },
    "Creatine Kinase MB Test": { price: 350, code: "CKM" },
    "Lipid Profile Test": { price: 350, code: "LPT" },
    "Ascitic Fluid Analysis Test": { price: 180, code: "AFA" },
    "Stool Culture Test": { price: 660, code: "SCT" },
    "Thyroid Profile Test": { price: 260, code: "TPT" },
    "Creatine Phosphokinase (CPK) Test": { price: 220, code: "CPK" },
    "Sickling Test": { price: 240, code: "SIC" },
    "Blood Group Test": { price: 120, code: "BGT" },
    "Serum Ascites Albumin Gradient (SAAG) Test": { price: 130, code: "SAG" },
    "Phosphorus Spot Urine Test": { price: 150, code: "PSU" },
    "VDRL Test CSF": { price: 70, code: "VTC" },
    "Bilirubin (Total, Direct & Indirect) Test": { price: 170, code: "BIL" },
    "Cerebrospinal Fluid (CSF) Analysis Test": { price: 180, code: "CSF" },
    "Blood Urea Nitrogen (BUN) Test": { price: 130, code: "BUN" },
    "Electrolytes (Na/K/Cl) Test": { price: 260, code: "ELE" },
    "Gamma-Glutamyl Transferase Test (GGT)": { price: 230, code: "GGT" },
    "Absolute Granulocyte Count Blood Test": { price: 150, code: "AGC" },
    "Urine Routine & Microscopic Examination Test": { price: 170, code: "URM" },
    "DLC (Differential Leucocyte Count) Test": { price: 130, code: "DLC" },
    "Glucose Post Prandial Test": { price: 90, code: "GPP" },
    "Glucose Tolerance Test (GTT 3)": { price: 660, code: "GT3" },
    "Albumin/Creatinine Ratio, Spot Urine Test": { price: 460, code: "ACR" },
    "Protein & Creatinine Ratio Urine Test": { price: 260, code: "PCR" },
    "Cell Count, Body Fluid Test": { price: 220, code: "CCB" },
    "Typhoid Test IGG & IGM": { price: 390, code: "TGM" },
    "Miscellaneous Fluid Analysis Test": { price: 180, code: "MFA" },
    "AFB Stain Test (Acid Fast Bacilli)": { price: 190, code: "ASB" },
    "Total T3 (Triiodothyronine) Test": { price: 180, code: "TT3" },
    "TLC (Total Leucocyte Count) Test": { price: 100, code: "TLC" },
    "Magnesium Test": { price: 260, code: "MGT" },
    "SGPT / ALT Test": { price: 150, code: "ALT" },
    "Anti Streptolysin O (ASO), Quantitative Test": { price: 480, code: "ASO" },
    "Troponin I, Rapid Card Test": { price: 1180, code: "TIC" },
    "Haemoglobin (Hb) Test": { price: 100, code: "HBT" },
    "Direct Coombs Test (DCT), Whole Blood EDTA Test": { price: 390, code: "DCT" },
    "Testosterone Total Test": { price: 340, code: "TTT" },
    "Malaria Antigen Detection Test (Rapid)": { price: 510, code: "MAD" },
    "Urine Pregnancy Test (UPT)": { price: 80, code: "UPT" },
    "Bilirubin Total Test": { price: 120, code: "BTT" },
    "Alkaline Phosphatase (ALP) Test": { price: 130, code: "ALP" },
    "Platelet Count Test": { price: 40, code: "PLT" },
    "Cholesterol Test": { price: 130, code: "CHT" },
    "FT4 (Free Thyroxine 4) Test": { price: 260, code: "FT4" },
    "Bilirubin Direct Test": { price: 120, code: "BDT" },
    "TLC & DLC Test": { price: 130, code: "TDT" },
    "VDRL Test": { price: 200, code: "VDT" },
    "Pleural Fluid Analysis Test": { price: 180, code: "PFA" },
    "Bleeding Time (BT) & Clotting Time (CT) Test": { price: 90, code: "BCT" },
    "Peripheral Blood Smear Test": { price: 130, code: "PBS" },
    "Sodium Test": { price: 130, code: "SOD" },
    "LDL Cholesterol Direct Test": { price: 260, code: "LDL" },
    "Adenosine Deaminase (ADA) Test Fluid": { price: 660, code: "ADF" },
    "Potassium Test": { price: 130, code: "POT" },
    "Hepatitis B Surface Antigen (HBsAg) Rapid Card Test": { price: 310, code: "HBS" },
    "Stool Occult Blood Test": { price: 120, code: "SOB" },
    "Prolactin Test (PRL)": { price: 480, code: "PRL" },
    "Treponema pallidium hemagglutination assay (tpha) Test": { price: 240, code: "TPH" },
    "Absolute Monocyte Count Blood Test": { price: 150, code: "AMC" },
    "ESR Test": { price: 100, code: "ESR" },
    "Fine Needle Aspiration Cytology (FNAC) Test": { price: 310, code: "FNA" },
    "India Ink Test": { price: 150, code: "IIT" },
    "Liver Function Extended Panel": { price: 520, code: "LFE" },
    "Haemogram (CBC+ESR)": { price: 350, code: "HCE" },
    "G6PD, Qualitative (Glucose-6-Phosphate Dehydrogenase) Test": { price: 660, code: "G6P" },
    "Microfilaria Detection Test": { price: 350, code: "MDT" },
        "Glucose Challenge Test (GCT)- 75 Grams Of Glucose": { price: 90, code: "GC7" },
        "Protein Spot Urine Test": { price: 220, code: "PSU" },
        "Albumin - Fluid Test": { price: 110, code: "AFT" },
        "Progesterone Test": { price: 440, code: "PGT" },
        "WIDAL Test By Slide Agglutination": { price: 110, code: "WTS" },
        "Lipid Profile Direct": { price: 390, code: "LPD" },
        "Sodium, Spot Urine Test": { price: 190, code: "SSU" },
        "Estimated Glomerular Filtration Rate (eGFR) Test": { price: 160, code: "EGF" },
        "Malaria Parasite Test (MP) Smear": { price: 110, code: "MPS" },
        "Troponin T, Rapid Card Test": { price: 590, code: "TRT" },
        "VDRL - RPR Titre (Semi Quant.) Test": { price: 150, code: "VRT" },
        "Fungal Stain Test": { price: 260, code: "FST" },
        "Phosphorus Test": { price: 130, code: "PHT" },
        "Chloride Test": { price: 120, code: "CLT" },
        "Lactate Dehydrogenase (LDH) Fluid Test": { price: 350, code: "LDF" },
        "Culture Aerobic, Throat Swab Test": { price: 700, code: "CTS" },
        "Culture Aerobic Tissue Test": { price: 700, code: "CAT" },
        "Culture Aerobic, Sputum Test": { price: 700, code: "CST" },
        "Culture Aerobic ET Secretion/Aspirate Test": { price: 700, code: "CES" },
        "Culture Aerobic Eye Swab Test": { price: 700, code: "CES" },
        "Culture Aerobic Pus Test": { price: 700, code: "CPT" },
        "PSA Test": { price: 700, code: "PSA" },
        "Culture Aerobic Ear Swab Test": { price: 700, code: "CES" },
        "Culture Aerobic Body Fluid Test": { price: 700, code: "CBF" },
        "Culture Aerobic Test CSF": { price: 700, code: "CAC" },
        "Culture Aerobic Vaginal Swab Test": { price: 700, code: "CVS" },
        "Culture Aerobic Swab Test": { price: 700, code: "CST" },
        "Culture Aerobic Tip Test": { price: 700, code: "CTT" },
        "Culture Aerobic Semen Test": { price: 700, code: "CST" },
        "HIV Early Screen Test": { price: 790, code: "HES" },
        "Glucose Tolerance Test (GTT 2)": { price: 440, code: "GT2" },
        "Luteinizing Hormone (LH) Test": { price: 440, code: "LHT" },
        "Urea Nitrogen 24 Hrs Urine Test": { price: 440, code: "UNU" },
        "Calcium 24 Hrs Urine Test": { price: 440, code: "CUT" },
        "Creatinine 24 Hrs Urine Test": { price: 440, code: "CUT" },
        "Creatinine Clearance 24 Hrs Urine Test": { price: 440, code: "CCU" },
        "Sodium 24 Hrs Urine Test": { price: 440, code: "SUT" },
        "Phosphorus 24 Hrs Urine Test": { price: 440, code: "PUT" },
        "Indirect Coombs (ICT) Serum Test": { price: 440, code: "ICT" },
        "Albumin Quantitative Urine 24 Hr Test": { price: 440, code: "AQU" },
        "Activated Partial Thromboplastin Time (APTT) Test": { price: 440, code: "APT" },
        "Uric Acid 24 Hrs Urine Test": { price: 440, code: "UAU" },
        "Potassium 24 Hrs Urine Test": { price: 440, code: "PKU" },
        "HCG Maternal Marker (Pregnancy) Test": { price: 440, code: "HMP" },
        "Protein 24 Hrs Urine Test": { price: 440, code: "PUH" },
        "Dengue Duo Screening Test": { price: 960, code: "DDS" },
        "Gestational Glucose Tolerance (GTT 4) Test": { price: 870, code: "GGT" },
        "Non Alcoholic Fatty Liver Disease (NAFLD) Fibrosis Score Test": { price: 880, code: "NFS" },
        "Chikungunya IgM, Rapid Card Test": { price: 880, code: "CRT" },
        "Filaria Antigen Detection Test": { price: 880, code: "FAD" },
        "Testosterone Free Test": { price: 1310, code: "TFT" },
        "8 Profile: 60 Parameters": { price: 750, code: "P8_60" },
        "10 Profile: 85 Parameters": { price: 1250, code: "P10_85" },
        "13 Profile: 95 Parameters": { price: 1750, code: "P13_95" },
        "Award - Male": { price: 3250, code: "AWD_M" },
        "Award - Female": { price: 3250, code: "AWD_F" },
        "Executive - Male": { price: 4150, code: "EXE_M" },
        "Executive - Female": { price: 4950, code: "EXE_F" },
        "Officer - Male": { price: 5250, code: "OFF_M" },
        "Officer - Female": { price: 6250, code: "OFF_F" }
    };

      const partners = [
        "AISSHPRA",
        "APGVB",
        "APGVB Pensioners Association",
        "ASA International",
        "Assam Gramin Vikash Bank",
        "Adhikosh Financial Advisory Pvt Ltd",
        "Adi Chitragupta Finance Limited",
        "Agora Microfinance",
        "Aishwarya MACC Society Ltd",
        "Ambitions Services",
        "Annapurna",
        "Arohan Financial Services Limited",
        "Aviral Finance",
        "Baghat Urban Co-op Bank Ltd",
        "Bangia Gramin Vikas Bank",
        "Bank of India",
        "CBC",
        "CCFID",
        "Cashpor",
        "Chhattisgarh Rajya Gramin Bank",
        "DCBS",
        "DULAL NGO",
        "ESAF HEALTH CARE SERVICES PVT LTD",
        "Hirbandh Ramkrishna Sarada Sevashrama",
        "Humana Financial Services",
        "IFFCO Bazar",
        "Indiabulls Housing Finance",
        "Jayam Community Resource Centre",
        "Janakalyan",
        "KBS Local Bank",
        "Kamal Fincap Private Limited",
        "M-INSURE CHANNEL",
        "Muthoot",
        "Maddox Consultancy Services Pvt Ltd",
        "Madhyanchal Gramin Bank",
        "Maharashtra Gramin Bank",
        "Midland Microfin",
        "Mitrata",
        "Muthoot Capital",
        "NABFINS Limited",
        "Namra Finance",
        "North East Small Finance Bank",
        "North East Small Finance Bank - SHG",
        "Pahal Finance",
        "Panchawati",
        "Paschim Banga Gramin Bank",
        "People's Forum",
        "Projects",
        "Pune District Central Co-op bank",
        "Rohtak Central Cooperative Bank",
        "SEBA RAHARA",
        "Sampurna Training and Entrepreneurship Programme",
        "Sarala Development & Microfinance Pvt Ltd",
        "Satya Microcapital",
        "Servitium Micro Finance Pvt Ltd",
        "Share India Fincap",
        "Shepays Financial Services Pvt Ltd",
        "Sindhuja Microcredit",
        "Sonata Finance",
        "South India Finvest Pvt Ltd",
        "Sudhir HUF",
        "Sugamya",
        "Svatantra",
        "Swabhimaan Sales & Services Pvt Ltd",
        "Swarnodhayam Credits Pvt Ltd",
        "TATA Capital",
        "Utkarsh SFB",
        "Uttar Banga Kshetriya Garmin Bank",
        "Uttar Bihar Gramin Bank",
        "Uttrayan",
        "VFS"
      ];

export default TEST_CATALOG;
export { partners };